name: EmbeddingScratchwork

channels:
  - conda-forge

dependencies:
  - python=3.11
  - backoff
  - numpy
  - openai
  - requests

  # For development
  - flake8
  - parameterized
  - pylint

  # Notebooks
  - ipykernel
  - tabulate

  # PyPI
  - pip
  - pip:
    - pylint-actions
