[tool.poetry]
name = "embeddingscratchwork"
version = "0.1.0"
description = "Scratch work for embeddings"
authors = [
    "David Vassallo <vassallo.davidm@gmail.com>",
    "Eliah Kagan <degeneracypressure@gmail.com>",
]
license = "0BSD"
readme = "README.md"
packages = [
    { include = "embed" },
]

[tool.poetry.dependencies]
python = "^3.8"
backoff = "^2.2.1"
blake3 = "^0.3.3"
numpy = "^1.24.3"
openai = "^0.27.6"
requests = "^2.30.0"

[tool.poetry.group.dev.dependencies]
attrs = "^23.1.0"
flake8 = { version = "^6.0.0", python = ">=3.8.1,<4.0" }
parameterized = "^0.9.0"
pylint = "^2.17.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
