name: Lint Python code

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  pylint:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Install pylint-sarif (unofficial fork)
        run: pipx install pylint-sarif-unofficial

      - name: Install pylint-exit
        run: pipx install pylint-exit

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v15

      - name: Make editable install
        run: pip install -e .

      - name: Run pylint, output annotations
        run: |
          (shopt -s globstar; pylint -f actions -- **/*.py || pylint-exit "$?")

      - name: Run pylint, output SARIF
        run: (shopt -s globstar; pylint2sarif -- **/*.py)

      - name: Upload SARIF to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pylint.sarif
