name: Check Markdown

on:
  push:
  pull_request:
  schedule:
    - cron: '0 16 * * *'

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-latest
    steps:
    - name: Check out source repository
      uses: actions/checkout@v3
    - name: Check Markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
