name: Test

on: [push, pull_request]

jobs:
  test:
    name: Unit Tests

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.10', '3.9', '3.8', '3.7']

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Substitute Python version
        run: |
          perl -i -spwe 's/^ *- python=\K.+$/$pyver/' -- \
              -pyver=${{ matrix.python-version }} environment.yml

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v15

      - name: Run Unit Tests
        run: python -m unittest -v
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
