name: Test

on: [push, pull_request]

jobs:
  check-for-api-key:
    name: Check for OpenAI API key
    runs-on: ubuntu-latest
    steps:
      - name: Check OPENAI_API_KEY repository secret
        run: |
          grep -q '^sk-' <<<'${{ secrets.OPENAI_API_KEY }}'

  test:
    name: Unit Tests

    needs: check-for-api-key

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.10', '3.9', '3.8', '3.7']

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Substitute Python version
        run: |
          perl -i -spwe 's/^ *- python=\K.+$/$pyver/' -- \
              -pyver=${{ matrix.python-version }} environment.yml

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v15

      - name: Print Python version
        run: python -V

      - name: Set up mutex
        if: >-
          vars.TESTS_CI_NONBLOCKING != 'true' &&
          vars.TESTS_CI_NONBLOCKING != 'yes' &&
          vars.TESTS_CI_NONBLOCKING != '1'
        uses: EliahKagan/actions-mutex@v2

      - name: Run Unit Tests
        run: python -m unittest -v
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TESTS_CACHE_EMBEDDING_CALLS: 'yes'
          TESTS_LOGGING_LEVEL: 'INFO'
