name: Test

on: [push, pull_request]

jobs:
  check-for-api-key:
    name: Check for OpenAI API key
    runs-on: ubuntu-latest
    steps:
      - name: Check OPENAI_API_KEY repository secret
        run: grep -q '^sk-' <<<'${{ secrets.OPENAI_API_KEY }}'

  read-blocking-config:
    name: Read blocking configuration
    runs-on: ubuntu-latest
    steps:
      - name: Read TESTS_CI_NONBLOCKING variable
        run: |
          # Allowed values are 'false', 'true', 'no', 'yes', '0', '1', and ''.
          if grep -qx '' <<<"$TESTS_CI_NONBLOCKING"; then
              # Nonblocking mode is implicitly off, so we WILL use the mutex.
              echo 'No actions variable TESTS_CI_NONBLOCKING.' >&2
              echo 'Treating it as if set to false.' >&2
              echo 'To make your intentions clear, set the variable.' >&2
              echo 'https://docs.github.com/en/actions/learn-github-actions/variables' >&2
              echo "use-mutex=true" >>"$GITHUB_OUTPUT"
          elif grep -Eqxi 'false|no|0|' <<<"$TESTS_CI_NONBLOCKING"; then
              # Nonblocking mode is explicitly off, so we WILL use the mutex.
              echo "use-mutex=true" >>"$GITHUB_OUTPUT"
          elif grep -Eqxi 'true|yes|1' <<<"$TESTS_CI_NONBLOCKING"; then
              # Nonblocking mode is on, so we will NOT use the mutex.
              echo "use-mutex=false" >>"$GITHUB_OUTPUT"
          else
              printf 'Unrecognized value "%s"\n' "$TESTS_CI_NONBLOCKING" >&2
              exit 1
          fi
        env:
          TESTS_CI_NONBLOCKING: ${{ vars.TESTS_CI_NONBLOCKING }}

  test:
    name: Unit Tests

    needs: [check-for-api-key, read-blocking-config]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.10', '3.9', '3.8', '3.7']

    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Substitute Python version
        run: |
          perl -i -spwe 's/^ *- python=\K.+$/$pyver/' -- \
              -pyver=${{ matrix.python-version }} environment.yml

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v15

      - name: Print Python version
        run: python -V

      - name: Debug use-mutex configuration
        run: echo '${{ needs.read-blocking-config.outputs.use-mutex }}'

      - name: Set up mutex
        if: needs.read-blocking-config.outputs.use-mutex
        uses: EliahKagan/actions-mutex@v2

      - name: Run Unit Tests
        run: python -m unittest -v
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TESTS_CACHE_EMBEDDING_CALLS: 'yes'
          TESTS_LOGGING_LEVEL: 'INFO'
